// <auto-generated />
namespace IW5Gallery.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201805071712243_GalleryDB_V4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201805071712243_GalleryDB_V4));
        
        string IMigrationMetadata.Id
        {
            get { return "201805071512220_201805071712243_GalleryDB_V4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
